// auto generated by scripts/i18n.ts
import React from 'react';

/* eslint-disable */
export interface I18nMessages {
  name: {
    t: 'zh' | 'en';

    v: undefined;
  };
  n: {
    t: '{n}' | 'en: {n}';

    v: {
      n: any;
    };
  };
  c: {
    t: '<s>{c}</s>' | 'en: <s>{c}</s>';

    v: {
      c: any;

      s: (chunks: React.ReactNode) => React.ReactNode;
    };
  };
}

export type I18nMessageKeys = keyof I18nMessages;

export type I18nTranslate = <T extends I18nMessageKeys>(
  key: T,
  ...values: I18nMessages[T]['v'] extends {} ? [I18nMessages[T]['v']] : []
) => I18nMessages[T]['t'];
