import { globSync } from 'glob';
import path from 'path';
import { getTsTypesFromRes } from 'typed-icu-message';
import fs from 'fs-extra';
import prettier from 'prettier';
import prettierConfig from '../prettier.config';
(async () => {
  const jsonFiles = globSync('src/i18n/*.json');
  const all: any = {};
  for (const json of jsonFiles) {
    const locale = path.basename(json).replace('.json', '');
    all[locale] = fs.readJsonSync(path.resolve(json));
  }
  const typedCode = getTsTypesFromRes(all);
  fs.writeFileSync(
    path.resolve('src/i18n/types.ts'),
    await prettier.format(
      `
  // auto generated by scripts/i18n.ts
  ${typedCode}`,
      { parser: 'typescript', ...prettierConfig },
    ),
  );
})();
